apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timofeev-pvc
  namespace: timofeev-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 4Gi