apiVersion: apps/v1
kind: Deployment
metadata:
  name: timofeev-bot
  namespace: timofeev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timofeev-bot
  template:
    metadata:
      labels:
        app: timofeev-bot
    spec:
      containers:
      - name: bot
        image: cr.yandex/crpo7tdod3sj8k3of2r6/taskbot:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: timofeev-ns
spec:
  type: ClusterIP
  selector:
    app: timofeev-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080