apiVersion: apps/v1
kind: Deployment
metadata:
  name: timofeev-bot
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timofeev-bot
  template:
    metadata:
      labels:
        app: timofeev-bot
    spec:
      containers:
      - name: bot
        image: {{ .Values.image.bot.repository }}:{{ .Values.image.bot.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | quote }}
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PORT
          value: "{{ .Values.postgres.port }}"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
