apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: timofeev-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
