apiVersion: apps/v1
kind: Deployment
metadata:
  name: timofeev-bot
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timofeev-bot
  template:
    metadata:
      labels:
        app: timofeev-bot
    spec:
      containers:
      - name: bot
        image: {{ .Values.image.bot.repository }}:{{ .Values.image.bot.tag }}
        ports:
        - containerPort: 8080
        env:
        # db-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_PORT
        # secret
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: TOKEN
        # secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
