apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: timofeev-db
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: 5432
